### ISSUE TITLE
Completed 401 Unauthorized

### ISSUE THREAD

**Issue by chenkovsky** [platanus/activeadmin_addons#169]
when I use selected_list. it send ajax to server, but it seems not authorized. how to solve it.

**Comment by chenkovsky** [comment]
I find where is the problem, I disabled download_link. but activeadmin checks download_link. if json is not in download_link. it will response 401.

**Comment by ldlsegovia** [comment]
I'm assuming you are using the `url` option. If so, you need to ensure the url provided is authorized. It's not related with the gem.

Please, reopen providing more details if I'm missing something.

**Comment by tatethurston** [comment]
@chenkovsky Thank you for replying with your fix -- you saved me quite some time.

In `config/initializers/active_admin.rb` if you set `admin.download_links` to any array that does not include `:json` then GET requests for selected_list will fail. You do not need to use the url option to encounter this.

**Comment by thisismydesign** [comment]
Seems like the comment with the solution was removed. Out-of-the-box API requests with JSON format to `ActiveRecord` resources will not work because of [this](https://github.com/activeadmin/activeadmin/blob/ef75c41747489d9d96bddd8f638c5fe50034b749/lib/active_admin/resource_controller.rb#L56-L67). This is quite unexpected and took me some time to figure out.

Here's workaround that will also place a download link on index pages which maybe not what you want:

```
ActiveAdmin.setup do |config|
  config.namespace :admin do |admin|
    admin.download_links = [:json]
  end
end
```

Would be great to mention this in the readme.
