### ISSUE TITLE
Custom url to ToggleBoolBuilder

### ISSUE THREAD

**Issue by kunashir** [platanus/activeadmin_addons#204]
I need to use custom url for `toggle_bool_column` because of nested resource. I've haven't found any way for this and made my own:
https://github.com/kunashir/activeadmin_addons/commit/0cd91be0c7bfc62ff64d84e9131ec414268ec73c
but it has two problem:
1. I do not know how I cant make next:
```ruby
column(:active) do |content|
  toggle_bool_column :active, url: auto_url_for(content)
end
```
I want this because I need access to resource.
For now I call it directly:
```ruby
column(:active) do |content|
   ActiveAdminAddons::ToggleBoolBuilder.new(self, content, :active, url: auto_url_for(content)).render
end
```

2. I do not know is it really useful feature for someone other than me.

**Comment by mf222** [comment]
Hi @kunashir, your solution seems to be useful for the case that you expose. If you feel like it could be useful in the future, you could open a pull request with your solution following the rules [mentioned here](https://github.com/platanus/activeadmin_addons#contributing). You already have the fork and the solution in order to contribute :)

**Comment by kunashir** [comment]
@mf222 Looks like new version of the gem also resolve this problem and the issue can be closed.
