### ISSUE TITLE
is already defined error

### ISSUE THREAD

**Issue by amanders23** [platanus/activeadmin_addons#217]
Hi, No matter what I have at the first level, I get error ___ is already define.  I can't figure out what's causing this.

`f.input :product_id, as: :nested_select,
                       level_1: {
                         attribute: :org_id
                       },
                       level_2: {
                         attribute: :product_id
                       }

class Product < ActiveRecord::Base
   belongs_to :org
   
class Transaction < ActiveRecord::Base
  belongs_to :org

class Org < ActiveRecord::Base
  has_many :products
  has_many :transactions

ActiveAdmin.register Transaction, :namespace => :admin do
permit_params  :org_id

ActiveAdmin.register Product, :as => "Products/Services" do
permit_params : :org_id

ActiveAdmin.register Org do
 permit_params :name

Any ideas? 
   `

**Comment by jodar** [comment]
I'm getting the exact same error. The form is pretty standard, 2 fields.

**Comment by chaumo** [comment]
Same problem here after upgrading to > 1.0.0 (was working fine on 0.12)

The problem seems to be because level_1 attribute (country_id) in my case already exists in the model, but AA (or AA addons) is trying to create a virtual attribute for the form and [raises the error](https://github.com/platanus/activeadmin_addons/blob/43f4eb7a118a9b726abee8f48a7d4b2983ea8e83/lib/activeadmin_addons/support/input_helpers/input_methods.rb#L61) if it already exists. 

In my case it's: 
*MODEL* which *belongs_to -> city* which *belongs_to -> country* but for easier filtering & db indexing I've also added a 'direct' *model belongs to -> country*

Any way to solve this issue? 

```
f.input :city_id, as: :nested_select,
        minimum_input_length: 2,
        level_1: {attribute: :country_id},
        level_2: {attribute: :city_id}
```

**Comment by ty-me** [comment]
Does this merged with master branch ?
