### ISSUE TITLE
tag_input doesn’t seem to work with nested virtual attribute

### ISSUE THREAD

**Issue by wowinter13** [platanus/activeadmin_addons#254]
I have UserGroup model which have has_many :trade_lanes. Each trade lane has classic methods: commodities_list and commodities_list=(values) (works like usual tags). But when I'm trying to update commodities_list :
``` ruby
f.has_many :relevant_tradelanes, allow_destroy: true, new_record: true do |x|
  x.input :commodities_list, as: :tags, collection: CommoditiesList.first.some_values
end
```

Ofc, params are permitted. But it always tries to create virtual_#{method}_attr even if above mentioned methods exist.
as: :boolean works normally.
Tried to permit `:commodities_list` or `commodities_list: []`

Seems to be duplicated with @acollazomayer 250th issue.

**Comment by ldlsegovia** [comment]
Sorry, I don't understand the issue here...

I have defined:

```ruby
class Invoice < ActiveRecord::Base
  def some_list=(value)
    @some_list = value
  end

  def some_list
    ["A", "B", "C"]
  end
end
```

```ruby
ActiveAdmin.register Invoice do
  permit_params(some_list: [])

  form do |f|
    f.inputs "Details" do
      f.input :some_list, as: :tags, collection: ["A", "B", "C"]
      # ...
```

And the first time:

![image](https://user-images.githubusercontent.com/3026413/127378911-0e9bf23e-ea81-4c31-add0-d279159cd7a9.png)

After saving:

![image](https://user-images.githubusercontent.com/3026413/127379016-ac108d38-b582-4b8f-a61a-3fb4ed11b652.png)

As you say, the `virtual_some_list_attr` travels with the paramenters but it's ok, is something related to addons functionality.

![image](https://user-images.githubusercontent.com/3026413/127379221-cc611226-cc98-4c56-b69c-749864892abc.png)

If you edit the element, you will see the same as at the beginning because the data is read from `Invoice#some_list`

After saving again:

![image](https://user-images.githubusercontent.com/3026413/127382543-fe247bbf-bfd3-4760-9045-e58ae31957f8.png)

the `some_list` attribute travels inside the invoice correctly.

Please, provide more information and reopen if this is still an issue.  
Sorry for the delayed answer :)
