### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by Charly3X** [platanus/activeadmin_addons#28]
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined - after ajax search

**Comment by emilioeduardob** [comment]
Hey @Charly3X , that's probably because the fieldname your trying to display on the select is not `name`, this addon defaults to the field `name`, but you can set your own.
I've updated the docs to better note this. 
https://github.com/platanus/activeadmin_addons/commit/7a5cd9a78cb3a4a8ee25ae1fb06699c822ac954d#diff-4206755b98c333baa874be4a449be3acR8
