### ISSUE TITLE
webpacker support

### ISSUE THREAD

**Issue by caifara** [platanus/activeadmin_addons#298]
I'm trying to move from sprockets to webpacker which activeadmin now officially supports. This (really helpful) gem is keeping us from upgrading for now.

Are there plans to submit an npm package?

**Comment by rjherrera** [comment]
@caifara Hi! We are discussing how to address this in the best way. As soon as we have an answer we will let you know!

**Comment by baka-san** [comment]
> @caifara Hi! We are discussing how to address this in the best way. As soon as we have an answer we will let you know!

Update on this?

**Comment by blackjid** [comment]
we could open up the discussion here :)

**Comment by rjherrera** [comment]
Hi again! Before addressing this I have a couple of questions/concerns for anyone to answer:
1. What are the necessary steps for this change? Would we need to publish an npm library that includes every js file bundled in this gem? What about css files? Maybe following the same steps the ActiveAdmin project did is the right way to go, what do you guys think?
1. Does this change mean we would be dropping support for sprockets? Will this change cause a problem for projects that don’t use webpacker?

**Comment by sgara** [comment]
Hi there, I could give my 2 cents here as I did the work on active admin. I suppose there are other paths possible but that was the best I could come up with. 
- rework js to use plain es6 syntax, ready to be non-published, and generate a bundle (we used rollup as rails does) compatible with sprockets. At this step, you can switch vendored dependencies to package.json dependencies if possible. 
- publish the package to npm

That should be it pretty much. And you don’t have to drop support for sprockets apps you can keep compatibility with both sprockets and webpacker thanks to rollup bundling. 
For css you don’t have much to change, except if you use `asset-url` or similar rails helpers. I also had to change imports directives to relative paths in the process. 

You can pretty much get the step-by-step approach [here](https://github.com/activeadmin/activeadmin/pulls?q=is%3Apr+author%3Asgara+is%3Aclosed)

Nb. I might take a look at it at some point since I also use this gem (thanks for the work btw!) and currently just copied the source in my project which isn’t that great.

**Comment by djalmaaraujo** [comment]
Any news here?

**Comment by rjherrera** [comment]
#319 is merged and we should be making a new release soon. Webpacker is supported in master!
