### ISSUE TITLE
Date Time Picker: Format date and time, date disappear after save 

### ISSUE THREAD

**Issue by stankovicjovana** [platanus/activeadmin_addons#315]
I am trying to format date in the Date Time Picker in format:
 ``` month/day/year hour:minute am/pm  ```

I went though [date-time-picker-doc](https://github.com/platanus/activeadmin_addons/blob/master/docs/date-time-picker.md) and [jqplugins/datetimepicker](https://xdsoft.net/jqplugins/datetimepicker/#hours12).
I need help to see what am if I am missing something or the problem is not in my config. :) 

When click on calendar icon, and picker shows up I would like to see date in this and time like 12:47pm
<img width="405" alt="Screenshot 2020-07-03 at 12 48 41 PM" src="https://user-images.githubusercontent.com/47898918/86466703-69406b80-bd34-11ea-8f74-ec85e4337adf.png">

If I set 
 ```
# config/initializers/activeadmin_addons.rb
  config.datetime_picker_input_format = '%m-%d-%Y %H:%M'

# ActiveAdmin.register Event ....
f.input :start_time, as: :date_time_picker,
      picker_options: {
        format_date:'d-m-Y',
        format_time:'h:m a'
      }
```
I get this view with time date formatted as YYYY/MM/DD, also time on time picker stacked with 7 minutes which is not shown in the result time :
<img width="406" alt="Screenshot 2020-07-03 at 2 24 23 PM" src="https://user-images.githubusercontent.com/47898918/86469148-203ee600-bd39-11ea-8428-d04b1d0869db.png">

After submitting the form, and open again to update the record, we see: 
<img width="416" alt="Screenshot 2020-07-03 at 2 33 05 PM" src="https://user-images.githubusercontent.com/47898918/86469783-6a749700-bd3a-11ea-9234-43b12774dfa5.png">
Just to think that this part is fixed, buuut then after save, the date I gone 🙀
<img width="397" alt="Screenshot 2020-07-03 at 2 37 24 PM" src="https://user-images.githubusercontent.com/47898918/86469955-b9bac780-bd3a-11ea-9499-a2f14c8af967.png">

Any ideas and help is highly appreciated! Thanks

**Comment by rjherrera** [comment]
Hi there! The format thing is a bit confusing because one format is used by the backend in the initializer ([ruby strftime](https://apidock.com/ruby/DateTime/strftime)) and the other one is used by the datetimepicker plugin ([php format](https://www.php.net/manual/en/function.date.php)).

For the 7 minutes thing, you were on the right path, but there was a little error because the expected format for minutes is `i` and not `m`. As we are in July, the format was displaying a `07`.

To fix that the code is this:

```ruby
format_time: 'h:i a'
```

Another detail is that you should also include the full date format in the input options:
```ruby
f.input :start_time, as: :date_time_picker,
                     picker_options: {
                       format: 'd-m-Y h:i a',
                       format_date: 'd-m-Y',
                       format_time: 'h:i a'
                     }
```

Finally, the format for the `datetime_picker_input_format` config option in the initializer should be in ruby format. This one is the one displayed initially in the datepicker. For the format you want to use, the code would be this:
```ruby
config.datetime_picker_input_format = '%d-%m-%Y %I:%M %P'
```

With those changes you should be alright! Let me know if that works!
