### ISSUE TITLE
Any plan for releasing a new version after 1.7.1?

### ISSUE THREAD

**Issue by oboxodo** [platanus/activeadmin_addons#331]
There are a lot of changes since 1.7.1 which was released on March 23, 2019.

Do you have any schedule to release a new version of the gem?

If not, do you consider `master` to be stable-enough to point our Gemfile to it and depend on it as it is?

**Comment by rjherrera** [comment]
Hi @oboxodo thanks for reeacching out! I think `master` is stable enough though we haven't made a release yet because we are mainly still using the version without webpacker. When we actually migrate our internal products we will be able to provide adequate QA for the webpacker version and release a new version, with everything.

I feel like it's not responsible from our side to release it when we haven't stressed it enough. That being said, we've tested it and it seems alright. Also, we know a few people from outside our organization are using master in their Gemfiles, so you can use it and feel free to give your feedback if anything comes up! We'll try to provide help if needed.

I will close this issue but don't worry, we are discussing how to approach the new release!

**Comment by oboxodo** [comment]
@rjherrera Yeah, we're already depending on some of the unreleased changes. We just don't like depending on unreleased code.

Some of those commits were submitted by my teammates @mateusg and @dkniffin: https://github.com/platanus/activeadmin_addons/commits?author=mateusg and https://github.com/platanus/activeadmin_addons/commits?author=dkniffin.
