### ISSUE TITLE
Version 1.8.0. and 1.8.1. pulled from RubyGems, breaking build

### ISSUE THREAD

**Issue by filipkis** [platanus/activeadmin_addons#357]
Hi guys, 

We just noticed today that version 1.8.0 and 1.8.1 were pulled from RubyGems which suddenly caused all our CI to break. Quickly I couldn't find any obvious mention of critical issues that would cause you to pull the gem. Still if there is, it would still be desired to leave older releases there, but put the disclaimer in the changelog that new ones should be used. 

Thanks

**Comment by rjherrera** [comment]
Hi there @filipkis! We are very sorry, we didn't handle the last update correctly, as you say we should have left those versions and warned to update to the new ones. We'll make sure it doesn't happen again. 

The reason behind the unusual update was that, by mistake, we were including vendor files into the gem, so those versions were around 80MB instead of the usual <1MB. Still, we shouldn't have pulled those versions from RubyGems, sorry for the problems caused. We will update the changelog accordingly.
