### ISSUE TITLE
select input data-attributes overwritten by activeadmin_addons

### ISSUE THREAD

**Issue by why-el** [platanus/activeadmin_addons#371]
The following code in activeadmin_addons: 

```
 class ActiveAdmin::Inputs::SelectInput < Formtastic::Inputs::SelectInput
      def input_html_options
        super.merge(data: { tags: @options[:tags].present? })
      end
    end
  end
```

does not allow users to add custom data attributes. When a user adds `input_html: {data: 'my-data'}` to the input, it gets overwritten by the above code. This makes it impossible to use libraries dependent on such attributes, such as Stimulus. 

The `InputBase` has the same issue, which is the use of `merge`. I think in both cases it should be `super.deep_merge`.

**Comment by fabn** [comment]
We were just bitten by this issue. Would you accept a PR or please include the proposed change in https://github.com/platanus/activeadmin_addons/issues/371#issuecomment-937869745

**Comment by inyerade** [comment]
Hi,
any news to fix this?

**Comment by difernandez** [comment]
This seems to have been fixed as of v2 beta, as the code in question [now uses deep_merge and also doesn't even touch the data attributes](https://github.com/platanus/activeadmin_addons/pull/448/files#diff-f92e349ecf029befc84c4b33a22bd42c30796f0c46cd4e042ad02ab0125caf11R4). Because of that I'm closing this issue, let us know if it's still a problem though!
