### ISSUE TITLE
Tagging with collection, allowing new values

### ISSUE THREAD

**Issue by wvteijlingen** [platanus/activeadmin_addons#70]
Thanks for this addon collection! Is there any way I could use the Select2 tag input with a collection, while also allowing users to create new tags? If I add the `collection` option I seem to lose the ability to create new tags.

The input is defined as follows:

```ruby
f.input :tag_ids, as: :tags, collection: ActsAsTaggableOn::Tag.all
```

**Comment by ldlsegovia** [comment]
Hi @wvteijlingen you're welcome! we decide to disable the ability to create new tags, because `collection` can be related to models containing multiple attributes, validations, etc. So, if you want to create nested data I think you should use [nested resources](http://activeadmin.info/docs/5-forms.html).
Don't get me wrong. I think this could be a good feature (you can try with a PR) I'm just explaining why I disabled the ability.
