### ISSUE TITLE
How can i use 'nested_select' if table haven't id column??

### ISSUE THREAD

**Issue by hotanlamvnn** [platanus/activeadmin_addons#89]
I have 3 table: Category, Post, Voucher

```
Voucher belongs_to Post
Post belongs_to Category
```

Table `Category` haven't id column, primary_key is `code`
How can i use `nested_select` in this case?

In AdminVoucher:

```
      f.input :post_id, as: :nested_select,
                  minimum_input_length: 0,
                  level_1: {
                    attribute: :category_code,
                    url: '/admin/categories'
                  },
                  level_2: {
                    fields: [:title],
                    display_name: :title,
                    attribute: :post_id
                  }
```

List all categories displayed. However, in select list,  i can not chosen and click.

**Comment by hotanlamvnn** [comment]
Seem like the key `category` have problem. 
It's ok after i changed table name `Category` to another name

**Comment by ldlsegovia** [comment]
@hotanlamvnn 
Do you see some js error?
What is the url when you are looking for categories and the parameters?
What is the url when you are looking for posts and the parameters?

**Comment by hotanlamvnn** [comment]
@ldlsegovia no errors
`"/admin/categories?order=name_desc&q%5Bgroupings%5D%5B0%5D%5Bm%5D=or&q%5Bgroupings%5D%5B0%5D%5Bname_contains%5D=&q%5Bcombinator%5D=and"`

`"/admin/posts?order=title_desc&q%5Bgroupings%5D%5B0%5D%5Bm%5D=or&q%5Bgroupings%5D%5B0%5D%5Btitle_contains%5D=&q%5Bcombinator%5D=and&q%5Bcategory_code_eq%5D=-1"`

**Comment by mf222** [comment]
Hi @hotanlamvnn, it's been a while since your issue, but it's better late than never. As you noted it is not supported yet. By default we connect the level with its model through the id, basically because is the way in which Rails connects the models.

Your issue has encorauge us to add a feat to allow user to relationate levels throght different attributes. You can follow the enhancment here #184 .

Greetings!
